### ISSUE TITLE
无法转换，提示没有代理

### ISSUE THREAD

**Issue by ycg31** [qier222/proxy-provider-converter#2]
问题如题，我使用其他的api链接转换是有的

**Comment by ArmstrongKing** [comment]
我也是同样的问题 求修复啊啊啊

**Comment by qier222** [comment]
麻烦提供一下链接指向的yaml config文件，将关键敏感信息替换掉

**Comment by GodDai** [comment]
clash 日志提示
> FATA[0000] Parse config error: proxy group[0]: 'Proxy' not found 

原链接指向的yaml config如下
```
proxies:
  - xxxx
  - xxxx
proxy-groups:
  - name: 手动选择
    type: select
    proxies:
      - xxxxx
  - name: 节点选择
    type: select
    proxies:
      - 手动选择
      - 自动选择
      - 故障切换
      - DIRECT
  - name: 国外网站
    type: select
    proxies:
      - 节点选择
      - DIRECT
      - 自动选择
      - 故障切换
  - name: NETFLIX
    type: select
    proxies:
      - xxxxxx
  - name: 国外媒体
    type: select
    proxies:
      - 节点选择
      - 自动选择
      - 故障切换
      - DIRECT
  - name: 电报吹水
    type: select
    proxies:
      - 节点选择
      - 自动选择
      - 故障切换
      - DIRECT
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 500
    proxies:
      - xxxxxxxx
  - name: 故障切换
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 500
    proxies:
      - xxxxx
rules:
 - DOMAIN-SUFFIX,local,DIRECT
 - xxxxx
```
rules太长不贴了 

转化后
```
proxies:
  - name: xxx
    server: xxxxx
    port: 18000
    type: ssr
    cipher: aes-256-cfb
    password: Uk92CS
    protocol: auth_aes128_sha1
    obfs: http_simple
    protocol-param: xxxx
    obfs-param: www.baidu.com
    udp: true
```
